//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gorsel_vize.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_stajyer
    {
        public int sid { get; set; }
        public string stajyer_ad { get; set; }
        public string stajyer_soyad { get; set; }
        public string stajyer_kullanıcıad { get; set; }
        public string stajyer_sifre { get; set; }
    }
}
