//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gorsel_vize.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ibas
    {
        public int ibasid { get; set; }
        public string ibas_ad { get; set; }
        public string ibas_kulad { get; set; }
        public string ibas_sifre { get; set; }
    }
}
