//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gorsel_vize.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_sbas
    {
        public int sbasid { get; set; }
        public string sbas_ad { get; set; }
        public string sbas_kulad { get; set; }
        public string sbas_sifre { get; set; }
    }
}
